# Generated by Django 2.1.2 on 2018-12-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioPedania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrebarrio', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecalle', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoLampara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrelampara', models.CharField(max_length=20)),
                ('pvp', models.FloatField(blank=True, default=0, null=True)),
                ('amortizacion', models.FloatField(blank=True, default=0, null=True)),
                ('actualprecio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoLuminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreluminaria', models.CharField(max_length=30)),
                ('pvp', models.FloatField(blank=True, default=0, null=True)),
                ('amortizacion', models.FloatField(blank=True, default=0, null=True)),
                ('actualprecio', models.DateTimeField(auto_now_add=True)),
                ('codigolampara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CatalogoLampara')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresoporte', models.CharField(max_length=30)),
                ('pvp', models.FloatField(blank=True, default=0, null=True)),
                ('amortizacion', models.FloatField(blank=True, default=0, null=True)),
                ('actualprecio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuadroMando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoindentificacion', models.CharField(max_length=12)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('tipocuadro', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('salidasutilizadas', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('mgtentrada', models.FloatField(blank=True, default=0, null=True)),
                ('fachada', models.BooleanField(blank=True, null=True)),
                ('alimentacionfn', models.BooleanField(blank=True, null=True)),
                ('alimentacion3fn', models.BooleanField(blank=True, null=True)),
                ('codigobarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.BarrioPedania')),
                ('codigocalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CatalogoCalle')),
            ],
        ),
        migrations.CreateModel(
            name='EquiposMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoidentificacion', models.CharField(max_length=12)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('kwcontrato', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('numeroactiva', models.CharField(blank=True, max_length=10, null=True)),
                ('numeroreactiva', models.CharField(blank=True, max_length=10, null=True)),
                ('monofasico', models.BooleanField(blank=True, null=True)),
                ('lecturadirecta', models.BooleanField(blank=True, null=True)),
                ('lecturaindirecta', models.BooleanField(blank=True, null=True)),
                ('codigobarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.BarrioPedania')),
                ('codigocalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CatalogoCalle')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoLuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('implanterenovacion', models.DateTimeField(auto_now_add=True)),
                ('codigobarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.BarrioPedania')),
                ('codigocalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CatalogoCalle')),
                ('codigocuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CuadroMando')),
                ('codigoluminaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CatalogoLuminaria')),
                ('codigosoporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.CatalogoSoporte')),
            ],
        ),
        migrations.CreateModel(
            name='ViaPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretipovia', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='cuadromando',
            name='codigocontadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.EquiposMedida'),
        ),
        migrations.AddField(
            model_name='catalogocalle',
            name='codigotipovia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_publico.ViaPublica'),
        ),
    ]
