# Generated by Django 2.1.2 on 2018-12-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioPedania',
            fields=[
                ('codigobarrio', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombrebarrio', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'barrio_pedania',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoCalles',
            fields=[
                ('codigocalle', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombrecalle', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'catalogo_calles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoLamparas',
            fields=[
                ('codigolampara', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombrelampara', models.CharField(max_length=20)),
                ('pvp', models.SmallIntegerField(blank=True, null=True)),
                ('amortizacion', models.SmallIntegerField(blank=True, null=True)),
                ('actualprecio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo_lamparas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoLuminarias',
            fields=[
                ('codigoluminaria', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombreluminaria', models.CharField(max_length=30)),
                ('pvp', models.SmallIntegerField(blank=True, null=True)),
                ('amortizacion', models.SmallIntegerField(blank=True, null=True)),
                ('actualprecio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo_luminarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoSoportes',
            fields=[
                ('codigosoporte', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombresoporte', models.CharField(max_length=30)),
                ('pvp', models.SmallIntegerField(blank=True, null=True)),
                ('amortizacion', models.SmallIntegerField(blank=True, null=True)),
                ('actualprecio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo_soportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuadroMando',
            fields=[
                ('cuadrocodigo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('codigoindentificacion', models.CharField(max_length=12)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('tipocuadro', models.SmallIntegerField()),
                ('salidasutilizadas', models.SmallIntegerField(blank=True, null=True)),
                ('mgtentrada', models.SmallIntegerField(blank=True, null=True)),
                ('fachada', models.BooleanField(blank=True, null=True)),
                ('alimentacionfn', models.BooleanField(blank=True, db_column='alimentacionFN', null=True)),
                ('alimentacion3fn', models.BooleanField(blank=True, db_column='alimentacion3FN', null=True)),
            ],
            options={
                'db_table': 'cuadro_mando',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposMedida',
            fields=[
                ('codigocontadores', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('codigoidentificacion', models.CharField(max_length=12)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('kwcontrato', models.SmallIntegerField(blank=True, null=True)),
                ('numeroactiva', models.CharField(blank=True, max_length=10, null=True)),
                ('numeroreactiva', models.CharField(blank=True, max_length=10, null=True)),
                ('monofasico', models.BooleanField(blank=True, null=True)),
                ('lecturadirecta', models.BooleanField(blank=True, null=True)),
                ('lecturaindirecta', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipos_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoLuz',
            fields=[
                ('codigopuntodeluz', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('implanterenovacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'punto_luz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViaPublica',
            fields=[
                ('codigotipovia', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombretipovia', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'via_publica',
                'managed': False,
            },
        ),
    ]
