# Generated by Django 2.1.2 on 2018-12-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_publico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogolampara',
            name='amortizacion',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catalogoluminaria',
            name='amortizacion',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catalogosoporte',
            name='amortizacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuadromando',
            name='salidasutilizadas',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadromando',
            name='tipocuadro',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equiposmedida',
            name='kwcontrato',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
