# Generated by Django 2.1.2 on 2018-12-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_publico', '0002_hola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hola',
        ),
    ]
